In [17]:
import numpy as np
# 1D array
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# Broadcasting automatically aligns shapes
print(a + b)  # Each element in `a` gets added to each row in `b`



[[11 12 13]
 [21 22 23]
 [31 32 33]]
